In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("https://raw.githubusercontent.com/sunnysavita10/Statistics_With_Python/main/Iris.csv")

In [4]:
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [7]:
#Random Sampling
random_sample=data.sample(10)

In [8]:
random_sample

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
103,104,6.3,2.9,5.6,1.8,Iris-virginica
91,92,6.1,3.0,4.6,1.4,Iris-versicolor
134,135,6.1,2.6,5.6,1.4,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica
97,98,6.2,2.9,4.3,1.3,Iris-versicolor
83,84,6.0,2.7,5.1,1.6,Iris-versicolor
55,56,5.7,2.8,4.5,1.3,Iris-versicolor
24,25,4.8,3.4,1.9,0.2,Iris-setosa
125,126,7.2,3.2,6.0,1.8,Iris-virginica
26,27,5.0,3.4,1.6,0.4,Iris-setosa

In [9]:
#Systematic Sampling
sys_sample=data.iloc[10:30:2]

In [10]:
sys_sample

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
10  11            5.4           3.7            1.5           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa

In [45]:
#Cluster Sampling
clusters = np.random.choice(np.arange(1,151), size=6, replace=False)

In [46]:
clusters

array([105, 138,  55,  92,  18, 133])

In [47]:
cluster_sample = data[data['Id'].isin(clusters)]

In [48]:
cluster_sample

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
17,18,5.1,3.5,1.4,0.3,Iris-setosa
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
91,92,6.1,3.0,4.6,1.4,Iris-versicolor
104,105,6.5,3.0,5.8,2.2,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica

In [5]:
#stratified Sampling
startified_sample = data.groupby('Species', group_keys=False).apply(lambda x: x.sample(2))

In [6]:
startified_sample

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
29,30,4.7,3.2,1.6,0.2,Iris-setosa
17,18,5.1,3.5,1.4,0.3,Iris-setosa
90,91,5.5,2.6,4.4,1.2,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor
108,109,6.7,2.5,5.8,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica